server:
  port: 8001

mybatis:
  type-aliases-package: com.zhu.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#对外暴露的微服务名字
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zhu
    password: 357715

#eureka服务配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001-hystrix #自定义hystrix服务名称信息
    prefer-ip-address: true  #访问路径可以显示id地址

#info信息配置
info:
  app.name: zhu-springcloud
  company.name: xiaozhu888.top